version: '3.3'

networks:
  database:

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - database
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=develop
      - ME_CONFIG_BASICAUTH_PASSWORD=develop
    networks:
      - database
    ports:
      - 8081:8081

  # express:
  #   build: .
  #   container_name: todolist-express
  #   restart: always
  #   environment:
  #     - DEBUG=false
  #     - MONGO_URL=mongo
  #     - MONGO_PORT=27017
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - database
  #   depends_on:
  #     - mongo
